[project]
name = "chws_tool"
dynamic = ["version"]
description = "Utility for OpenType chws/vchw features"
authors = [
    { name = "Koji Ishii", email = "kojii@chromium.org" }
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
dependencies = [
    "east-asian-spacing>=1.4.5",
]

[project.urls]
repository = "https://github.com/googlefonts/chws_tool"

[dependency-groups]
dev = [
    "black>=24.8.0",
    "pyrefly>=1.2.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.16.1",
    "tox>=4.25.0",
    "tox-uv>=1.13.1",
]

[project.scripts]
add-chws = 'chws_tool.add_chws:main'

[build-system]
requires = ["setuptools>=82.0.1", "setuptools-scm>=10.2.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = "tests"

[tool.ruff.lint]
ignore = [
]

[tool.setuptools_scm]
# https://github.com/pypa/setuptools-scm
version_file = "src/chws_tool/_version.py"
# https://github.com/dependabot/dependabot-core/issues/12340
fallback_version = "0.0.0"
